name: Generate Snake Animation

on:
  schedule: # يشغل يومياً
    - cron: "0 0 * * *"
  workflow_dispatch: # تقدر تشغله يدوي
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: issambouhchych
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Snake"
          add: "dist/github-contribution-grid-snake.svg"
